services:
  - type: web
    name: erp-backend
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      cd frontend && npm install && npm run build
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
